"""empty message

Revision ID: 4e44de0a233e
Revises: None
Create Date: 2015-02-22 15:20:07.842449

"""

# revision identifiers, used by Alembic.
revision = '4e44de0a233e'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
